# Generated by Django 4.0.4 on 2022-04-22 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocular.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Followers',
            new_name='Followers',
        ),
        migrations.RenameModel(
            old_name='User_Notifications',
            new_name='UserNotifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_posts',
        ),
        migrations.DeleteModel(
            name='Post_Reactions',
        ),
        migrations.AddField(
            model_name='postreactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocular.tags'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocular.tags'),
        ),
        migrations.DeleteModel(
            name='Post_Categories',
        ),
    ]
