# Generated by Django 4.0.4 on 2022-04-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocular', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='hashtag',
        ),
    ]
