# Generated by Django 4.0.4 on 2022-04-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocular', '0002_rename_category_photo_hashtag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNotification',
            new_name='PostMessage',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
