# Generated by Django 4.0.4 on 2022-04-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocular', '0003_rename_usernotification_postmessage_user_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='hashtag',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(to='ocular.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/default-avatar.png', upload_to='images/'),
        ),
    ]
