# Generated by Django 4.0.4 on 2022-04-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocular', '0004_remove_photo_hashtag_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hashtag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
