# Generated by Django 4.0.4 on 2022-05-12 16:46

from django.db import migrations, models
import ocular.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocular', '0006_alter_photo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=ocular.models.get_default, upload_to='images/'),
        ),
    ]
